FROM node:16-alpine3.14

RUN apk --no-cache add --virtual .builds-deps build-base python3

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

RUN npm i -g ts-node

COPY package*.json ./
COPY tsconfig.json ./

RUN npm install

COPY . .

RUN ts-node -v

ENTRYPOINT ["ts-node"]
CMD ["./src/app.ts"]